/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.lookandfeel.RoundedBorder;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import Processor.Registers;

/**
 *
 * @author parke
 */
public class Register_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Registers
     */
    public Register_GUI() {
        initComponents();
        this.setBorder(new RoundedBorder(new Color(70, 70, 70), 00, 15));
        this.pc1.setGridColor(new Color(70, 70, 70));
        this.pc.setGridColor(new Color(70, 70, 70));
        this.lowHigh.setGridColor(new Color(70, 70, 70));
        this.registers.setGridColor(new Color(70, 70, 70));

        configTable(this.pc);
        configTable(this.pc1);
        configTable(this.lowHigh);
        configTable(this.registers);

        //this.pc.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        //this.pc1.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        //this.lowHigh.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        //this.registers.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        //Register_GUI.pc.setT
    }

    private static void configTable(JTable table) {
        table.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        TableColumnModel colModel = table.getColumnModel();
        colModel.getColumn(0).setPreferredWidth(90);
        colModel.getColumn(1).setPreferredWidth(250);
        colModel.getColumn(2).setPreferredWidth(80);
        colModel.getColumn(3).setPreferredWidth(90);
    }

    public static synchronized void updateVals() {
        for (int i = 1; i <= 31; i++) {
            setRegisterRow(registers, i - 1, Registers.getRegister(i));
        }

        setRegisterRow(pc, 0, Registers.getPc());

        setRegisterRow(lowHigh, 0, Registers.getLow());
        setRegisterRow(lowHigh, 1, Registers.getHigh());
        lowHigh.setValueAt(((long) Registers.getHigh() << 32) | (long) Registers.getLow(),
                2, 3);
    }

    private static void setRegisterRow(JTable table, int row, int val) {
        String bin = String.format("%32s", Integer.toBinaryString(val)).replaceAll(" ", "0");
        String hex = String.format("%8s", Integer.toHexString(val)).replaceAll(" ", "0");

        table.setValueAt(bin, row, 1);
        table.setValueAt(hex, row, 2);
        table.setValueAt(val, row, 3);
    }

    public static String intToHexString(int val) {
        return String.format("%8s", Integer.toHexString(val)).replaceAll(" ", "0");
    }

    public static String intToBinString(int val) {
        return String.format("%32s", Integer.toBinaryString(val)).replaceAll(" ", "0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pc1 = new javax.swing.JTable();
        pc = new javax.swing.JTable();
        lowHigh = new javax.swing.JTable();
        registers = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);

        pc1.setBackground(new java.awt.Color(102, 102, 102));
        pc1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pc1.setForeground(new java.awt.Color(204, 204, 204));
        pc1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Name", "Bin", "Hex", "Dec"}
            },
            new String [] {
                "Register", "Bin", "Hex", "Dec"
            }
        ));
        pc1.setEnabled(false);
        pc1.setOpaque(false);

        pc.setBackground(new java.awt.Color(102, 102, 102));
        pc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pc.setForeground(new java.awt.Color(204, 204, 204));
        pc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PC", null, null, null}
            },
            new String [] {
                "Register", "Bin", "Hex", "Dec"
            }
        ));
        pc.setEnabled(false);
        pc.setGridColor(new java.awt.Color(51, 51, 51));
        pc.setOpaque(false);

        lowHigh.setBackground(new java.awt.Color(102, 102, 102));
        lowHigh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lowHigh.setForeground(new java.awt.Color(204, 204, 204));
        lowHigh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Low", null, null, null},
                {"High", null, null, null},
                {"Combined", null, null, null}
            },
            new String [] {
                "Register", "Bin", "Hex", "Dec"
            }
        ));
        lowHigh.setEnabled(false);
        lowHigh.setGridColor(new java.awt.Color(204, 204, 204));
        lowHigh.setOpaque(false);

        registers.setBackground(new java.awt.Color(102, 102, 102));
        registers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        registers.setForeground(new java.awt.Color(204, 204, 204));
        registers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null},
                {"6", null, null, null},
                {"7", null, null, null},
                {"8", null, null, null},
                {"9", null, null, null},
                {"10", null, null, null},
                {"11", null, null, null},
                {"12", null, null, null},
                {"13", null, null, null},
                {"14", null, null, null},
                {"15", null, null, null},
                {"16", null, null, null},
                {"17", null, null, null},
                {"18", null, null, null},
                {"19", null, null, null},
                {"20", null, null, null},
                {"21", null, null, null},
                {"22", null, null, null},
                {"23", null, null, null},
                {"24", null, null, null},
                {"25", null, null, null},
                {"26", null, null, null},
                {"27", null, null, null},
                {"28", null, null, null},
                {"29", null, null, null},
                {"30", null, null, null},
                {"31", null, null, null}
            },
            new String [] {
                "Register", "Bin", "Hex", "Dec"
            }
        ));
        registers.setEnabled(false);
        registers.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(lowHigh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable lowHigh;
    private static javax.swing.JTable pc;
    private javax.swing.JTable pc1;
    private static javax.swing.JTable registers;
    // End of variables declaration//GEN-END:variables
}
