package org.parker.mips.gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.components.FlatTabbedPane;
import org.parker.mips.architectures.mips.gui.RegisterGUI;
import org.parker.mips.gui.components.VerticalJLabel;
import org.parker.mips.gui.theme.ThemeHandler;

import javax.swing.*;
import java.awt.*;

public class test extends JPanel {
    private JPanel rootPanel;
    private FlatTabbedPane flatTabbedPane1;
    private JPanel emulatorPanel;
    private JPanel debugPanel;
    private JPanel projectPanel;

    public static void main(String... args) {
        UIManager.put("TabbedPane.tabHeight", UIManager.getInt("TabbedPane.tabHeight") - 30);
        ThemeHandler.init();

        JFrame frame = new JFrame();
        frame.setContentPane(new test());
        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public test() {
        $$$setupUI$$$();

        JLabel project = new VerticalJLabel("Project", new FlatSVGIcon("Images/Icons/SVG/projectDirectory.svg", 16, 16));
        JLabel debug = new VerticalJLabel("Debug", new FlatSVGIcon("Images/Icons/SVG/debugger.svg", 16, 16));
        JLabel emulatorState = new VerticalJLabel("Emulator State", new FlatSVGIcon("Images/Icons/SVG/memory.svg", 16, 16));


        flatTabbedPane1.removeAll();
        flatTabbedPane1.addTab("", projectPanel);
        flatTabbedPane1.setTabComponentAt(0, project);
        flatTabbedPane1.addTab("", debugPanel);
        flatTabbedPane1.setTabComponentAt(1, debug);
        flatTabbedPane1.addTab("", emulatorPanel);
        flatTabbedPane1.setTabComponentAt(2, emulatorState);
    }

    private void createUIComponents() {
        rootPanel = this;

        this.emulatorPanel = new RegisterGUI();
        this.debugPanel = new JPanel();
        this.projectPanel = new JPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel.setLayout(new BorderLayout(0, 0));
        flatTabbedPane1 = new FlatTabbedPane();
        flatTabbedPane1.setAutoscrolls(false);
        flatTabbedPane1.setHasFullBorder(false);
        flatTabbedPane1.setHideTabAreaWithOneTab(false);
        flatTabbedPane1.setTabHeight(10);
        flatTabbedPane1.setTabInsets(new Insets(5, 2, 5, 2));
        flatTabbedPane1.setTabPlacement(4);
        flatTabbedPane1.setTabWidthMode(FlatTabbedPane.TabWidthMode.compact);
        flatTabbedPane1.setTabsClosable(false);
        flatTabbedPane1.setTabsPopupPolicy(FlatTabbedPane.TabsPopupPolicy.never);
        rootPanel.add(flatTabbedPane1, BorderLayout.CENTER);
        flatTabbedPane1.addTab("Emulator State", emulatorPanel);
        flatTabbedPane1.addTab("Debug", debugPanel);
        flatTabbedPane1.addTab("Project", projectPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
